

@tenant=12345
@token=_t_o_k_e_n_
# @baseUrl=https://86rwdlo7w9.execute-api.us-east-1.amazonaws.com/dev/v1.0
@baseUrl=http://localhost:3000/dev/v1.0

@deviceId=01FXVHQ18KVG7TY06C4A9Z3DTM

## sample
POST {{baseUrl}}/{{tenant}}/device
Authorization: {{token}}

{
    "name" : "device-3",
    "ip" : "10.0.0.3"
}

### Get
GET {{baseUrl}}/{{tenant}}/device/{{deviceId}}
Authorization: {{token}}

### UPDATE
PUT {{baseUrl}}/{{tenant}}/device/{{deviceId}}
Authorization: {{token}}

{
    "name" : "device-3",
    "ip" : "10.0.0.6"
}


### DELETE
DELETE {{baseUrl}}/{{tenant}}/device/{{deviceId}}
Authorization: {{token}}
