

@tenant=12345
@token=_t_o_k_e_n_
@baseUrl=http://localhost:3000/dev/v1.0

@deviceId=01FXT6HTG4RXZHP93C7JHJG7SB

## sample
POST {{baseUrl}}/{{tenant}}/device
Authorization: {{token}}

{
    "name" : "device-3",
    "ip" : "10.0.0.3"
}

### Get
GET {{baseUrl}}/{{tenant}}/device/{{deviceId}}
Authorization: {{token}}

### UPDATE
PUT {{baseUrl}}/{{tenant}}/device/{{deviceId}}
Authorization: {{token}}

{
    "name" : "device-3",
    "ip" : "10.0.0.6"
}


### DELETE
DELETE {{baseUrl}}/{{tenant}}/device/{{deviceId}}
Authorization: {{token}}